# Generated by Django 5.2.17 on 2026-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image_url", models.URLField()),
                ("intro", models.TextField()),
                ("original_url", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("lyrics", models.TextField()),
                ("cover_url", models.URLField(blank=True)),
                ("original_url", models.URLField(unique=True)),
                (
                    "artists",
                    models.ManyToManyField(related_name="songs", to="music.artist"),
                ),
            ],
        ),
    ]
