# Generated by Django 5.2.17 on 2026-08-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="singer_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
