# Generated by Django 5.2.17 on 2026-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_song_singer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="wikipedia_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
