# Generated by Django 5.2.17 on 2026-08-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_artist_wikipedia_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="artist",
            name="intro",
            field=models.TextField(blank=True, default=""),
        ),
    ]
